---
- hosts: all
  sudo: yes
  vars:
    - git_email: "ksnavely@gmail.com"

  tasks:
    # OS stuff
    # nginx
    # build website

    - name: Update apt-cache
      apt: update_cache=yes

    - name: Install deps
      apt: name={{ item }} update_cache=yes
      with_items:
        - build-essential
        - git
        - vim
        - libssl1.0.0
        - libssl-dev
        - tmux
        - python-pip
        - python-dev
        - iotop
        - nginx=1.2.1*
        - runit=2.1.1*

    - name: Push the nginx config
      template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf

    - name: Allow Ansible git module to clone repositories
      file:
        state=directory
        mode=0755
        dest=/srv/website
        owner=vagrant
        group=vagrant

    - name: Grab the git repo
      git: repo=git@github.com:ksnavely/website.git 
           dest=/srv/website
           clone=yes
           update=no
           accept_hostkey=yes
      sudo: no

    - name: Get virtualenv
      pip: virtualenv

    - pip:
           virtualenv=/srv/website/venv
           requirements=/srv/website/website/requirements.txt

