---
- hosts: all
  sudo: yes
  vars:
    - git_email: "ksnavely@gmail.com"

  tasks:
    # OS stuff
    # nginx
    # build website

    - name: Update apt-cache
      apt: update_cache=yes

    - name: Install deps
      apt: name={{ item }} update_cache=yes
      with_items:
        - build-essential
        - curl
        - lsof
        - git
        - vim
        - libssl1.0.0
        - libssl-dev
        - tmux
        - python-pip
        - python-dev
        - iotop
        - nginx=1.4.6*
        - runit=2.1.1*

    - name: Push the nginx config
      template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf

    - name: Needed for runit
      template: 
        src=templates/docker_start.sh 
        dest=/srv/website/docker_start.sh
        mode=u+rwx

    - name: website user
      user: name=website

    - name: Set website srv as website user
      file:
        state=directory
        mode=0755
        dest=/srv/website
        owner=website
        group=website

    - name: Get virtualenv
      pip: name=virtualenv

    - pip:
           virtualenv=/srv/website/venv
           requirements=/srv/website/website/requirements.txt

    - name: Setup symlinks for runit in general
      file:
        state=link
        src=/etc/service
        dest=/service

    - name: Setup website sv dir
      file:
        state=directory
        dest=/etc/sv/website/supervise

    - name: Setup website sv log dir
      file:
        state=directory
        dest=/etc/sv/website/log/main

    - name: Setup website runit service
      template:
        src=templates/sv-website-run
        dest=/etc/sv/website/run
        mode=u+rwx

    - name: Setup website runit log service
      template:
        src=templates/sv-website-log-run
        dest=/etc/sv/website/log/run
        mode=u+rwx

    - name: Setup symlinks for runit for the website
      file:
        state=link
        src=/etc/sv/website
        dest=/etc/service/website

    - name: Setup nginx sv dir
      file:
        state=directory
        dest=/etc/sv/nginx/supervise

    - name: Setup nginx sv log dir
      file:
        state=directory
        dest=/etc/sv/nginx/log/main

    - name: Setup nginx runit service
      template:
        src=templates/sv-nginx-run
        dest=/etc/sv/nginx/run
        mode=u+rwx

    - name: Setup nginx runit log service
      template:
        src=templates/sv-nginx-log-run
        dest=/etc/sv/nginx/log/run
        mode=u+rwx

    - name: Setup symlinks for runit for the website
      file:
        state=link
        src=/etc/sv/nginx
        dest=/etc/service/nginx
